import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { createIdea } from "./actions";
import TransitionArrow from "@/components/transition-arrow";

export default async function VaultPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const supabase=await createClient();
 const {data:ideas}=await supabase.from("ideas").select("id,title,short_description,sector,market,confidentiality_level,created_at").order("created_at",{ascending:false});
 const params=await searchParams;
 return <>
 <header className="workspacePageHead"><span className="sectionKicker">خزنة الفرص</span><h1>الأفكار والفرص</h1><p>مساحة التقاط الفرصة قبل انتقالها إلى التحقق والتطوير داخل المختبر.</p></header>
 <section className="vaultCompose"><div className="vaultComposeIntro"><span>01</span><h2>سجّل الفرصة<br/>كما هي الآن.</h2><p>الهدف هنا ليس تجميل الفكرة، بل تثبيت سياقها الأولي قبل بدء دورة الفرضيات والأدلة.</p></div><div className="vaultForm">{params.error?<p className="error">تعذر حفظ الفكرة. تحقق من الحقول وحاول مرة أخرى.</p>:null}<form action={createIdea} className="form"><div className="grid2"><div className="field"><label>العنوان</label><input name="title" required/></div><div className="field"><label>وصف مختصر</label><input name="short_description"/></div><div className="field"><label>القطاع</label><input name="sector"/></div><div className="field"><label>السوق</label><input name="market"/></div><div className="field"><label>العميل</label><input name="customer"/></div><div className="field"><label>المشتري المحتمل</label><input name="potential_buyer"/></div><div className="field"><label>مصدر الفكرة</label><input name="idea_source"/></div><div className="field"><label>مستوى السرية</label><select name="confidentiality_level" defaultValue="P0"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></div></div><div className="field"><label>المشكلة</label><textarea name="problem"/></div><div className="field"><label>الحل الأولي</label><textarea name="initial_solution"/></div><div className="field"><label>ملاحظات</label><textarea name="notes"/></div><div><button className="button transitionButton" type="submit"><span>حفظ وفتح المختبر</span><TransitionArrow/></button></div></form></div></section>
 <section className="vaultArchive"><div className="workspaceSectionTitle"><span className="sectionKicker">الأرشيف</span><h2>الفرص المحفوظة</h2></div>{ideas?.length?<div className="ideaList">{ideas.map((idea,index)=><Link className="ideaRow" href={`/lab/${idea.id}`} key={idea.id}><span>{String(index+1).padStart(2,"0")}</span><div><small>{idea.sector||idea.market||"فرصة"}</small><strong>{idea.title}</strong><p>{idea.short_description||"بدون وصف مختصر"}</p></div><i>{idea.confidentiality_level}</i><span className="ideaRowAction"><span>فتح المختبر</span><TransitionArrow/></span></Link>)}</div>:<div className="editorialEmpty"><span>00</span><h2>لا توجد فرص محفوظة حتى الآن.</h2><p>ابدأ بتسجيل أول فرصة في النموذج أعلاه.</p></div>}</section>
 </>
}
