insert into public.store_products (
  slug,
  sku,
  title_ar,
  title_en,
  summary_ar,
  summary_en,
  product_type,
  status,
  price_sar,
  delivery_mode,
  license_tier,
  is_featured,
  preview_ar,
  preview_en,
  created_by,
  published_at,
  rights_status,
  rights_basis,
  rights_notes,
  rights_reviewed_at,
  delivery_status,
  delivery_notes,
  delivery_ready_at,
  checkout_status,
  checkout_notes,
  checkout_ready_at,
  source_attribution,
  product_version
)
select
  'payment-test-5-sar',
  'NW-TEST-PAY-005',
  'منتج تجريبي — اختبار الدفع',
  'Payment Test Product',
  'منتج تجريبي بقيمة 5 ريال لاختبار مسار الدفع والتأكيد والاستحقاق في نُموان.',
  'A SAR 5 test product for validating Numwan payment, confirmation, and entitlement flow.',
  'TOOLKIT',
  'PUBLISHED',
  5.00,
  'DIGITAL_ACCESS',
  'STANDARD',
  false,
  'هذا المنتج مخصص لاختبار بوابة الدفع فقط، ولا يمثل أصلًا تجاريًا للبيع العام.',
  'This product is for payment gateway testing only and is not a commercial asset.',
  p.created_by,
  now(),
  'CLEARED',
  'NUMWAN_INTERNAL',
  'Internal payment test product with no third-party content.',
  now(),
  'READY',
  'Digital entitlement only. No downloadable commercial files.',
  now(),
  'READY',
  'EdfaPay hosted checkout production test.',
  now(),
  'NUMWAN internal payment test',
  'test-1'
from public.store_products p
where p.slug='saudi-industrial-intelligence-v1'
on conflict (slug) do update
set
  price_sar=excluded.price_sar,
  status='PUBLISHED',
  rights_status='CLEARED',
  delivery_status='READY',
  checkout_status='READY',
  published_at=coalesce(public.store_products.published_at,now()),
  updated_at=now();
